### ISSUE TITLE
Replace cryptonite with crypton

### ISSUE THREAD

**Issue by Kleidukos** [haskell/wreq#154]
@ondrap `cryptonite` has been archived and deprecated in favour of `crypton`. Would you accept a PR migrating `wreq` to `crypton`? 

(The deprecation also impacts other packages by the author, like `memory`, `basement`, etc.)

**Comment by Kleidukos** [comment]
@ondrap can I add Github actions CI too?

**Comment by ondrap** [comment]
I'm not sure how this works on github (and to be honest, I never worked with github actions...).. but if you think it would help...

**Comment by ondrap** [comment]
Merged and released a new version.
